_packages/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
]

store/urls.py
from django.urls import path
from django.conf.urls.static import static
from _packages import settings

from . import views

app_name='store'
urlpatterns = [
    path('', views.store.as_view(), name='store'),
    path('product/<int:pk>', views.ProductItem.as_view(), name='product'),

    path('cart/', views.cart.as_view(), name='cart'),
    path('checkout/', views.checkout.as_view(), name='checkout'),
    
    path('update-item/', views.updateItem.as_view(), name='update-item'),
    path('process-order/', views.processOrder, name='process-order'),
]
if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/models.py
from distutils.command.upload import upload
from pyexpat import model
from django.db import models

# Create your models here.
from django.contrib.auth.models import User


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, null=True)
    email = models.EmailField(max_length=200, null=True)

    def __str__(self) -> str:
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=100, null=True)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    digital = models.BooleanField(default=False, null=True, blank=True)
    image = models.ImageField(upload_to='product_images/', null=True, blank=True)

    def __str__(self) -> str:
        return self.name
    
    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = 'static/images/placeholder.png'
        return url



class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False, null=True, blank=True)
    transaction_id = models.CharField(max_length=200, null=True)

    def __str__(self) -> str:
        return str(self.id)

    @property
    def shipping(self):
        shipping = False
        items = items = self.orderitem_set.all()
        for i in items:
            if i.product.digital == False:
                shipping = True
                break
        return shipping

    @property
    def get_cart_total(self):
        items = self.orderitem_set.all()
        total = sum([item.get_total for item in items])
        return total

    @property
    def get_cart_items(self):
        items = self.orderitem_set.all()
        total = sum([item.quantity for item in items])
        return total


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True, blank=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, blank=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total


class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True, blank=True)
    address = models.CharField(max_length=200, null=True)
    city = models.CharField(max_length=200, null=True)
    state = models.CharField(max_length=200, null=True)
    zipcode = models.CharField(max_length=200, null=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.address

store/views.py
from itertools import product
from django.shortcuts import render
from django.http import JsonResponse, HttpResponseNotFound
import json, datetime
from django.views import View
from django.views.generic import ListView, CreateView, DetailView

from store.models import *
from store.utils import cartData, cookieCart, guestOrder

class store(ListView):

    model = Product
    template_name = 'store/store.html'
    context_object_name = 'products'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        search = self.request.GET.get('search-area') or ''
        if (search):
            context['products'] = context['products'].filter(name__contains=search)
        
        context['search_area'] = search
        context['order'] = cartData(self.request, False)['order']
        return context


class ProductItem(DetailView):
    model = Product
    template_name = "store/productItem.html"
    context_object_name = "product"


class cart(View):
    def get(self, request):
        context = cartData(self.request)
        return render(request, 'store/cart.html', context)


class checkout(View):
    def get(self, request):
        context = cartData(self.request)
        return render(request, 'store/checkout.html', context)


def processOrder(request):

    data = json.loads(request.body)

    if request.user.is_authenticated:
        # check the order data
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        
    else:
        print('User is not logged in..')
        customer, order = guestOrder(request.COOKIES['cart'], data['form'])

    transactionId = datetime.datetime.now().timestamp()
    order.transaction_id = str(transactionId)
    # total = order.get_cart_total
    order.complete = True
    order.save()

    # check the shipping data
    if order.shipping:
        ShippingAddress.objects.create(
            customer=customer,
            order=order,
            address=data['shipping']['address'],
            city=data['shipping']['city'],
            state=data['shipping']['state'],
            zipcode=data['shipping']['zipcode'],
        )
        
    return JsonResponse('payment submitted..', safe=False)


class updateItem(View):
    def get(self, request):
        return HttpResponseNotFound(request)
    
    def post(self, request):
        data = json.loads(request.body)
        productId = data['productId']
        action = data['action']

        # authenticated user
        if request.user.is_authenticated:
            customer = request.user.customer
            order, created = Order.objects.get_or_create(customer=customer, complete=False)

            product = Product.objects.get(pk=productId)
            orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)
            if action == 'add':
                orderItem.quantity += 1
            elif action == 'remove':
                orderItem.quantity -= 1
            orderItem.save()

            if orderItem.quantity <= 0:
                orderItem.delete()
                data['remove'] = True
            else:
                data['total-price'] = order.get_cart_total
                data['item-quantity'] = orderItem.quantity
                data['item-price'] = orderItem.get_total
            data['total-items'] = order.get_cart_items
        else:          
            result = cookieCart(request.COOKIES['cart'])
            
            data['total-items'] = result['order']['get_cart_items']
            data['total-price'] = result['order']['get_cart_total']

            for item in result['items']:
                if (item['product'].id == int(productId)):
                    data['item-quantity'] = item['quantity']
                    data['item-price'] = item['get_total']
                    break

        return JsonResponse(data)

store/templates/store/cart.html
{% extends 'store/Main.html' %}
{% load static %}
{% block content %}

  <div class="row">
    <div class="col-lg-12">
      <div class="box-element">
        <a href="{% url 'store:store'%}" class="btn btn-outline-dark my-2 mx-2">&#x2190; Continue Shopping</a>
        <br><br>
        <hr>
        <table class="table">
          <tr>
            <th><h5>Items: <strong id="total-items">{{order.get_cart_items}}</strong></h5></th>
            <th><h5>Total: <strong id="total-price">${{order.get_cart_total|floatformat:2}}</strong></h5></th>
            <th>
              <a href="{% url 'store:checkout'%}" class="btn btn-success" style="float:right;">Checkout</a>
            </th>
          </tr>
        </table>
      </div>

      <br>
      <div class="box-element">
        <div class="cart-row">
          <div style="flex:2;"></div>
          <div style="flex:2;"><strong>Item</strong></div>
          <div style="flex:1;"><strong>Price</strong></div>
          <div style="flex:1;"><strong>Quantity</strong></div>
          <div style="flex:1;"><strong>Total</strong></div>
        </div>

        {% for item in items %}
        <div class="cart-row" id="{{item.product.id}}">
          <div style="flex:2;">
            <img src="{{item.product.imageURL}}" alt="" class="image-col">
          </div>
          <div style="flex:2;"><strong>{{item.product.name}}</strong></div>
          <div style="flex:1;"><strong>${{item.product.price|floatformat:2}}</strong></div>
          <div style="flex:1;">
            <p class="quantity" id="qte-{{item.product.id}}">{{item.quantity}}</p>
            <div class="quantity">
              <img data-product="{{item.product.id}}" data-action="add" src="{% static 'images/arrow-up.png'%}" alt="" class="chg-quantity update-cart">
              <img data-product="{{item.product.id}}" data-action="remove" src="{% static 'images/arrow-down.png'%}" alt="" class="chg-quantity update-cart">
            </div>
          </div>
          <div style="flex:1;"><strong id="price-{{item.product.id}}">${{item.get_total}}</strong></div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>

{% endblock content %}

store/templates/store/checkout.html
{% extends 'store/Main.html' %}
{% load static %}
{% block content %}

  <div class="row">
    <div class="col-12 col-xl-6">
      {% csrf_token %}
      {% if not request.user.is_authenticated or order.shipping%}
      <div class="box-element" id="form-wrapper">
        <form id="form">
          {% if not request.user.is_authenticated %}
          <div id="user-info" class="row px-4 pt-4">
            <div class="col-6">
              <input name="name" type="text" class="form-control" placeholder="Name" required>
            </div>
            <div class="col-6">
              <input name="email" type="email" class="form-control" placeholder="Email" required>
            </div>
          </div>
          {% endif %}

          {% if order.shipping %}
          <div id="shipping-info" class="row p-4">
            <hr>
            <p>Shipping Information:</p>
            <hr>

            <div class="col-6 mb-2">
              <input name="address" type="text" class="form-control" placeholder="Address">
            </div>
            <div class="col-6 mb-2">
              <input name="city" type="text" class="form-control" placeholder="City">
            </div>
            <div class="col-6 mb-2">
              <input name="state" type="text" class="form-control" placeholder="State">
            </div>
            <div class="col-6 mb-2">
              <input name="zipcode" type="text" class="form-control" placeholder="Zipcode">
            </div>
            <div class="col-6 mb-2">
              <input name="country" type="text" class="form-control" placeholder="Country">
            </div>

          </div>
          {% endif %}

          <div class="row p-4">
            <hr>
            <input id="form-button" class="btn btn-success btn-block" value="Continue" type="submit">
          </div>
        </form>
      </div>
      {% endif %}

      <br>
      <div id="payment-info" class="box-element p-2 mb-3 hidden">
        <!--button class="btn btn-outline-dark" id="make-payment" onclick='submitFormData()'>Make payment</button-->
        <div id="paypal-button-container"></div>
      </div>
    </div>
    
    <div class="col-12 col-xl-6">
      <div class="box-element p-3 mb-2">
        <a href="{% url 'store:cart'%}" class="btn btn-outline-dark">&#x2190; Back to Cart</a>
        <hr>

        <div class="row">
          <div class="col-6"><h3>Order Summary</h3></div>
          <div class="col-3"><h5 style="float:right;">Items:{{order.get_cart_items}}</h5></div>
          <div class="col-3"><h5 class="ms-4">Total:${{order.get_cart_total|floatformat:2}}</h5></div>
        </div>
        <hr>

        {% for item in items %}
        <div class="cart-row">
          <div style="flex:2">
            <img class="image-col" src="{{item.product.imageURL}}" alt="">
          </div>
          <div style="flex:2"><p>{{item.product.name}}</p></div>
          <div style="flex:1"><p>${{item.product.price|floatformat:2}}</p></div>
          <div style="flex:1"><p>x{{item.quantity}}</p></div>
          <div style="flex:1"><p>${{item.get_total|floatformat:2}}</p></div>
        </div>
        {% endfor %}

      </div>
    </div>
  </div>

  <script src="{% static 'js/checkout.js'%}" type="text/javascript"></script>

  <!-- Include the PayPal JavaScript SDK -->
  <script src="https://www.paypal.com/sdk/js?client-id=AR4GDM81vgyPvQf8jzFCK6cKledWQXa56l4G9hJu3yOyepOGEoV0-u8CIrWK8FV2N0BOa-p0IHwtR2V_&currency=USD"></script>

  <script>
    var total = {{order.get_cart_total}}
    // Render the PayPal button into #paypal-button-container
    paypal.Buttons({

    // Set up the transaction
    createOrder: function(data, actions) {
        return actions.order.create({
            purchase_units: [{
                amount: {
                    value: '0.04'//parseFloat(total).toFixed(2)
                }
            }]
        });
    },

    // Finalize the transaction
    onApprove: function(data, actions) {
        return actions.order.capture().then(function(orderData) {
            // Successful capture! For demo purposes:
            console.log('Capture result', orderData, JSON.stringify(orderData, null, 2));
            var transaction = orderData.purchase_units[0].payments.captures[0];
            alert('Transaction '+ transaction.status + ': ' + transaction.id + '\n\nSee console for all available details');

            // Replace the above to show a success message within this page, e.g.
            // const element = document.getElementById('paypal-button-container');
            // element.innerHTML = '';
            // element.innerHTML = '<h3>Thank you for your payment!</h3>';
            // Or go to another URL:  actions.redirect('thank_you.html');
        });
    }

    }).render('#paypal-button-container');
  </script>
  
{% endblock content %}

store/templates/store/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1, minimum-scale=1">
    
    <!-- vendor CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

    <!-- custom CSS -->
    <link rel="stylesheet" href="{% static 'css/main.css'%}">

    <!-- custom JS -->
    <script type="text/javascript">
      var user = "{{request.user}}";

      function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== ''){
          var cookies = document.cookie.split(';');
          for (var i=0; i<cookies.length; i++) {
            var cookie = cookies[i].trim();
            if (cookie.substring(0, name.length + 1) === (name+'=')){
              cookieValue = decodeURIComponent(cookie.substring(name.length+1));
              break;
            }
          }
        }
        return cookieValue;
      }
      var csrftoken = getCookie('csrftoken');
    </script>

    <title>Ecom</title>
</head>
<body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand mb-0 h1" href="{% url 'store:store'%}">Ecommerce</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'store:store'%}">Home</a>
          </li>
        </ul>
        <form method="get" action="{% url 'store:store'%}" class="d-flex" style="margin-right: 20px !important; max-width: 50%;">
          <input name="search-area" class="form-control me-2" type="search" placeholder="Search" aria-label="Search" value="{{search_area}}">
          <button class="btn btn-outline-dark" type="submit">Search</button>
        </form>
        <div class="d-flex form-inline my-2 my-lg-0">
          <a href="" class="btn btn-warning">Login</a>
          <a href="{% url 'store:cart'%}">
            <img id="cart-icon" src="{% static 'images/cart.png'%}" alt="cart">
          </a>
          <p id="cart-total">{% firstof order.get_cart_items '0' %}</p>
        </div>
      </div>
    </div>
  </nav>

  <div class="container">
    <br>
    {% block content %}
    
    {% endblock content %}
  </div>

  <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

  <!-- custom JS -->
  <script text="text/javascript" src="{% static 'js/cart.js'%}"></script>
</body>
</html>

store/templates/store/productItem.html
{% extends 'store/main.html' %}
{% load static %}

{% block content %}

<link rel="stylesheet" href="{% static 'css/product.css'%}">


<div class="container py-3 product-item">
    <div class="row">
        <div class="col-6">
            <div class="card-img-actions">
                <img src="{{product.imageURL}}" class="card-img img-fluid img" alt="...">
            </div>
        </div>
        <div class="col-6">
            <h2>{{product.name}}</h2>
            <h6>${{product.price}}</h6>
            <br>
            <h5>Description</h5>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus rerum neque magnam? Neque ea ab inventore pariatur aperiam, maiores voluptate maxime facilis reiciendis odit hic, voluptatem quaerat nisi. Laboriosam, perspiciatis.</p>
            
        </div>
    </div>
    <div class="row">
        <h5>Details</h5>
        
        <h6>brend:</h6>
        <h6>color:</h6>
        <h6>size:</h6>
        <h6>brend:</h6>
        <h6>brend:</h6>
    </div>
</div>



{% endblock content %}

store/templates/store/store.html
{% extends 'store/Main.html' %}
{% load static %}

{% block content %}

  <div class="row">

    {% for product in products %}
    <div class="col-xl-3 col-lg-4 col-6 mb-2">
      <div class="card box-element">

        <div class="card-img-actions">        
          <img src="{{product.imageURL}}" class="card-img img-fluid" width="96" height="350" alt="">
        </div>
        
        <div class="card-body bg-light text-center">
          <div class="mb-2">
              <h6 class=" mb-3">
                  <a href="{% url 'store:product' product.id %}" class="title mb-2" data-abc="true">{{product.name}}</a>
              </h6>
          </div>
  
          <h3 class="mb-0">${{ product.price|floatformat:2 }}</h3>
  
          <div class="text-muted mb-3">34 reviews</div>
  
          <button type="button" data-product="{{product.id}}" data-action="add" class="btn bg-cart add-btn update-cart"><i class="fa fa-cart-plus mr-2"></i> Add to cart</button>
  
          
        </div>
      </div>
    </div>
    {% endfor %}

  </div>

  <script>
    var items = document.getElementsByClassName('item');
    for (i=0; i<items.length; i++) {
      items[i].addEventListener('click', function(){
          var productId = this.dataset.product;
          window.location.href = "/product/"+productId.toString();
      });
  }
  </script>

{% endblock content %}